name: equipment-manager-app
services:
  db:
    build: ./db
    container_name: loan_db
    networks:
      - loan-network
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s

  backend:
    build: ./backend
    container_name: loan_backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    networks:
      - loan-network

  frontend:
    build: ./frontend
    container_name: loan_frontend
    ports:
      - "8081:80"
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    depends_on:
      - backend
    networks:
      - loan-network

networks:
  loan-network:
    name: "loan-network"
    driver: bridge